// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jhnet.proto
// Protobuf C++ Version: 5.29.3

#include "jhnet.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace jhnet {

inline constexpr SC_Echo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        number_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_Echo::SC_Echo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_EchoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_EchoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_EchoDefaultTypeInternal() {}
  union {
    SC_Echo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_EchoDefaultTypeInternal _SC_Echo_default_instance_;

inline constexpr CS_Echo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        number_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_Echo::CS_Echo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_EchoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_EchoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_EchoDefaultTypeInternal() {}
  union {
    CS_Echo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_EchoDefaultTypeInternal _CS_Echo_default_instance_;
}  // namespace jhnet
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_jhnet_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_jhnet_2eproto = nullptr;
const ::uint32_t
    TableStruct_jhnet_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::jhnet::CS_Echo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::jhnet::CS_Echo, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::jhnet::CS_Echo, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::jhnet::SC_Echo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::jhnet::SC_Echo, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::jhnet::SC_Echo, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::jhnet::CS_Echo)},
        {10, -1, -1, sizeof(::jhnet::SC_Echo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::jhnet::_CS_Echo_default_instance_._instance,
    &::jhnet::_SC_Echo_default_instance_._instance,
};
const char descriptor_table_protodef_jhnet_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013jhnet.proto\022\005jhnet\"*\n\007CS_Echo\022\016\n\006numbe"
    "r\030\001 \001(\r\022\017\n\007message\030\002 \001(\t\"*\n\007SC_Echo\022\016\n\006n"
    "umber\030\001 \001(\r\022\017\n\007message\030\002 \001(\t*L\n\010PacketId"
    "\022\010\n\004NONE\020\000\022\014\n\007CS_PING\020\351\007\022\014\n\007CS_ECHO\020\352\007\022\014"
    "\n\007SC_PING\020\321\017\022\014\n\007SC_ECHO\020\322\017b\006proto3"
};
static ::absl::once_flag descriptor_table_jhnet_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_jhnet_2eproto = {
    false,
    false,
    194,
    descriptor_table_protodef_jhnet_2eproto,
    "jhnet.proto",
    &descriptor_table_jhnet_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_jhnet_2eproto::offsets,
    file_level_enum_descriptors_jhnet_2eproto,
    file_level_service_descriptors_jhnet_2eproto,
};
namespace jhnet {
const ::google::protobuf::EnumDescriptor* PacketId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_jhnet_2eproto);
  return file_level_enum_descriptors_jhnet_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PacketId_internal_data_[] = {
    65536u, 262144u, 2001u, 1002u, 2002u, 1001u, };
bool PacketId_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, PacketId_internal_data_);
}
// ===================================================================

class CS_Echo::_Internal {
 public:
};

CS_Echo::CS_Echo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:jhnet.CS_Echo)
}
inline PROTOBUF_NDEBUG_INLINE CS_Echo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::jhnet::CS_Echo& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CS_Echo::CS_Echo(
    ::google::protobuf::Arena* arena,
    const CS_Echo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_Echo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.number_ = from._impl_.number_;

  // @@protoc_insertion_point(copy_constructor:jhnet.CS_Echo)
}
inline PROTOBUF_NDEBUG_INLINE CS_Echo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CS_Echo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.number_ = {};
}
CS_Echo::~CS_Echo() {
  // @@protoc_insertion_point(destructor:jhnet.CS_Echo)
  SharedDtor(*this);
}
inline void CS_Echo::SharedDtor(MessageLite& self) {
  CS_Echo& this_ = static_cast<CS_Echo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CS_Echo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_Echo(arena);
}
constexpr auto CS_Echo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CS_Echo),
                                            alignof(CS_Echo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_Echo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_Echo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_Echo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CS_Echo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_Echo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CS_Echo>(), &CS_Echo::ByteSizeLong,
            &CS_Echo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_Echo, _impl_._cached_size_),
        false,
    },
    &CS_Echo::kDescriptorMethods,
    &descriptor_table_jhnet_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_Echo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> CS_Echo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::jhnet::CS_Echo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CS_Echo, _impl_.message_)}},
    // uint32 number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CS_Echo, _impl_.number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CS_Echo, _impl_.number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 number = 1;
    {PROTOBUF_FIELD_OFFSET(CS_Echo, _impl_.number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(CS_Echo, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\7\0\0\0\0\0"
    "jhnet.CS_Echo"
    "message"
  }},
};

PROTOBUF_NOINLINE void CS_Echo::Clear() {
// @@protoc_insertion_point(message_clear_start:jhnet.CS_Echo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.number_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CS_Echo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CS_Echo& this_ = static_cast<const CS_Echo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CS_Echo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CS_Echo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:jhnet.CS_Echo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 number = 1;
          if (this_._internal_number() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_number(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "jhnet.CS_Echo.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:jhnet.CS_Echo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CS_Echo::ByteSizeLong(const MessageLite& base) {
          const CS_Echo& this_ = static_cast<const CS_Echo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CS_Echo::ByteSizeLong() const {
          const CS_Echo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:jhnet.CS_Echo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // uint32 number = 1;
            if (this_._internal_number() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_number());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CS_Echo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CS_Echo*>(&to_msg);
  auto& from = static_cast<const CS_Echo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jhnet.CS_Echo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_number() != 0) {
    _this->_impl_.number_ = from._impl_.number_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_Echo::CopyFrom(const CS_Echo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jhnet.CS_Echo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_Echo::InternalSwap(CS_Echo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.number_, other->_impl_.number_);
}

::google::protobuf::Metadata CS_Echo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_Echo::_Internal {
 public:
};

SC_Echo::SC_Echo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:jhnet.SC_Echo)
}
inline PROTOBUF_NDEBUG_INLINE SC_Echo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::jhnet::SC_Echo& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

SC_Echo::SC_Echo(
    ::google::protobuf::Arena* arena,
    const SC_Echo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_Echo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.number_ = from._impl_.number_;

  // @@protoc_insertion_point(copy_constructor:jhnet.SC_Echo)
}
inline PROTOBUF_NDEBUG_INLINE SC_Echo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void SC_Echo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.number_ = {};
}
SC_Echo::~SC_Echo() {
  // @@protoc_insertion_point(destructor:jhnet.SC_Echo)
  SharedDtor(*this);
}
inline void SC_Echo::SharedDtor(MessageLite& self) {
  SC_Echo& this_ = static_cast<SC_Echo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SC_Echo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_Echo(arena);
}
constexpr auto SC_Echo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SC_Echo),
                                            alignof(SC_Echo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_Echo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_Echo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_Echo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_Echo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_Echo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_Echo>(), &SC_Echo::ByteSizeLong,
            &SC_Echo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_Echo, _impl_._cached_size_),
        false,
    },
    &SC_Echo::kDescriptorMethods,
    &descriptor_table_jhnet_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_Echo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> SC_Echo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::jhnet::SC_Echo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SC_Echo, _impl_.message_)}},
    // uint32 number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_Echo, _impl_.number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_Echo, _impl_.number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 number = 1;
    {PROTOBUF_FIELD_OFFSET(SC_Echo, _impl_.number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(SC_Echo, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\7\0\0\0\0\0"
    "jhnet.SC_Echo"
    "message"
  }},
};

PROTOBUF_NOINLINE void SC_Echo::Clear() {
// @@protoc_insertion_point(message_clear_start:jhnet.SC_Echo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.number_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_Echo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_Echo& this_ = static_cast<const SC_Echo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_Echo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_Echo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:jhnet.SC_Echo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 number = 1;
          if (this_._internal_number() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_number(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "jhnet.SC_Echo.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:jhnet.SC_Echo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_Echo::ByteSizeLong(const MessageLite& base) {
          const SC_Echo& this_ = static_cast<const SC_Echo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_Echo::ByteSizeLong() const {
          const SC_Echo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:jhnet.SC_Echo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // uint32 number = 1;
            if (this_._internal_number() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_number());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_Echo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_Echo*>(&to_msg);
  auto& from = static_cast<const SC_Echo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jhnet.SC_Echo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_number() != 0) {
    _this->_impl_.number_ = from._impl_.number_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_Echo::CopyFrom(const SC_Echo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jhnet.SC_Echo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_Echo::InternalSwap(SC_Echo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.number_, other->_impl_.number_);
}

::google::protobuf::Metadata SC_Echo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace jhnet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_jhnet_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
